### ISSUE TITLE
Game crash with some mods

### ISSUE THREAD

**Issue by inexcode** [inexcode/Woohooer#6]
There are reports about this mod crashing the game and deactivating all mods if loaded with some other mods (unknown yet)

**Comment by Weirn** [comment]
Hey there I can provide a small list of mods that I have removed while I was trying to figure out why it was acting up. I removed the callistan race, avali race, ratkin race, apparello 2, and based on the error log at the time VGP (Vegetable Garden) mods. Now I'm not sure about apparello 2 because I think it might actually work based on comments on steam but that is what I am able to gather.
